services:
  - type: web
    name: portfolio-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    region: oregon
    runtime: python
    autoDeploy: true
    branch: main
    repo: https://github.com/shahidshaikh79/stock-portfolio-web-app
